### ISSUE TITLE
Baud process crashing

### ISSUE THREAD

**Issue by pallix** [samuelventura/baud#6]
I have read a loop in my program that call this function:

```elixir
  def handle_call({:read, count}, _from, state) do
    res = case Baud.readn(state.serial_pid, count, state.timeout) do
            {:to, data} ->             {:timeout, data}
 
#              Logger.info "Timeout in baud"
            {:ok, data} ->
              {:ok, data}
          end
    {:reply, res, state}
  end

```  

Typical value for `count` is 1024 and `timeout` 50.

Sometimes, after a several minutes, the Baud process crashes:

```elixir
15:24:08.879 [error] GenServer #PID<0.199.0> terminating
** (stop) exited in: GenServer.call(#PID<0.200.0>, {:get_and_update, #Function<3.131405667/1 in Baud.readn/3>}, 100)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    [...]
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.198.0>): {:read, 1024}
State: %{serial_pid: #PID<0.200.0>, timeout: 50}
```

```elixir
Client #PID<0.198.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    [...]
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

**Comment by samuelventura** [comment]
- Are you running this on Linux?
- What baudrate are you using?

**Comment by pallix** [comment]
Yes Linux. 921600.

**Comment by samuelventura** [comment]
What handshaking mechanism are you using? At that speed your serial-read-buffer may loose data if not emptying fast enough. Loosing data would cause not finding as many bytes as expected when reading. Also, a 50ms timeout requires that your writing process warranties putting 1024 every time. Failure to do so would result in Baud not finding enough bytes in the given time frame. I am not sure if Baud can handle a continuous workload like that without the help of proper handshake and buffer sizing.

**Comment by pallix** [comment]
Thanks for your detailed reply.

I don't have a handshaking mechanism but I did not observe any lost of data during the tests.

> Failure to do so would result in Baud not finding enough bytes in the given time frame.

Shouldn't the remaining bytes just be returned with the timeout?

**Comment by samuelventura** [comment]
You are right. Baud should return the partial data. It looks like the GenServer.call timeout is kicking in before the inner timeout. The precaution of doubling the GenServer.call timeout is not helping either. The inner timeout is soft implemented with monotonic_time/sleep calls. Their granularity may not be small enough to ensure a 50ms timeout never goes above the 100ms hard limit of the GenServer.call. Some threads point :timer.sleep to have a minimum of 10ms. There is also the inherent OS process switching ~20ms drift. Not trying to disregard the possibility of a Baud bug, my point is that there is no sure way to deal with soft timing issues. Generously adjusting your timeout may be the practical thing to do.

**Comment by samuelventura** [comment]
What would help me debug this issue is:
- Run added long.exs with `time mix long` and report your findings. Change the timeout from 60 below and above and report effects on your side. You need two serial ports for that. Setup your ports at the top of the script. The goal here is to grasp the effect of different timeout values to the number of partial packets reported.
- Elaborate on your use case at hand so that I better understand what you are trying to accomplish and maybe suggest an alternative or, if the use case is general enough, complement Baud in a way that helps you.

Baud works fine for my current use case which is talking to low speed Modbus devices and text controlled instruments. I know however that a simple task like waiting for a new line terminated barcode string at an undetermined point in the future has no direct implementation in Baud right now because of its non-blocking nature. A packetizing callback API, like Erlang Ports have, would be a better fit for that.

**Comment by samuelventura** [comment]
This is my output with 60ms timeout. This was run on a Ubuntu16/64x VM on Window10/64X host using StarTech ICUSB2328I. Two timeouts in ~70min and no process crashing. 2KB packets timing out very close at 1.9KB.

```bash
samuel@samuel-VirtualBox:~/baud$ time mix long
{38796, "Timeout", 1984}
{83271, "Timeout", 1989}

real	69m18.911s
user	1m45.504s
sys	1m13.048s
```

**Comment by pallix** [comment]
I cannot reproduce the bug with the latest version of `sniff`.

Do you want me to run the test script nonetheless?

**Comment by samuelventura** [comment]
Only if it adds value to you.

**Comment by pallix** [comment]
I had the bug again with the master version of `baud` and `sniff`

**Comment by pallix** [comment]
I adapted your long script to try to reproduce the bug but I get a different error:

```
=ERROR REPORT==== 3-Apr-2018::14:58:49 ===
** Generic server <0.136.0> terminating
** Last message in was {get_and_update,#Fun<Elixir.Baud.3.58935676>}
** When Server state == {#Ref<0.966806314.710541317.211829>,
                         <<"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789">>}
** Reason for termination ==
** {{badmatch,{er,"read mismatch"}},
    [{'Elixir.Baud',read_n,5,[{file,"lib/Baud.ex"},{line,189}]},
     {'Elixir.Baud','-readn/3-fun-0-',3,[{file,"lib/Baud.ex"},{line,115}]},
     {'Elixir.Agent.Server',handle_call,3,
                            [{file,"lib/agent/server.ex"},{line,16}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
** Client <0.74.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},
    {'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,828}]},
    {elixir_compiler_1,'-__FILE__/1-fun-0-',3,
                       [{file,"script/long.exs"},{line,12}]},
    {'Elixir.Enum',reduce_range_inc,4,[{file,"lib/enum.ex"},{line,2940}]},
    {elixir_compiler_1,'__FILE__',1,[{file,"script/long.exs"},{line,10}]},
    {elixir_compiler,dispatch,6,[{file,"src/elixir_compiler.erl"},{line,85}]},
    {elixir_lexical,run,3,[{file,"src/elixir_lexical.erl"},{line,18}]},
    {elixir_compiler,quoted,3,[{file,"src/elixir_compiler.erl"},{line,27}]}]
** (EXIT from #PID<0.74.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:er, 'read mismatch'}
        (baud) lib/Baud.ex:189: Baud.read_n/5
        (baud) lib/Baud.ex:115: anonymous fn/3 in Baud.readn/3
        (elixir) lib/agent/server.ex:16: Agent.Server.handle_call/3
        (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```



```
cat script/long.exs
tty1 = case :os.type() do
  {:unix, :linux} -> "ttyABC"
end

{:ok, pid1} = Baud.start_link([device: tty1, speed: 921600])


to = 100

for i <- 1..100000 do

  case Baud.readn pid1, 1024, to do
    {:ok, _long} -> IO.inspect {i, "Packet complete"}
    {:to, part} ->
      IO.inspect {i, "Timeout", byte_size(part)}
  end
end
```

**Comment by pallix** [comment]
I cannot reproduce the bug with the script, only with the system at work. I can reproduce the bug when the baud is set at `9600` and the serial line is sent a lot of data.

**Comment by pallix** [comment]
```
** (exit) exited in: GenServer.call(#PID<0.8702.0>, {:read, 1024}, 5000)
    ** (EXIT) exited in: GenServer.call(#PID<0.8703.0>, {:get_and_update, #Function<3.58935676/1 in Baud.readn/3>}, 800)
        ** (EXIT) time out
    (elixir) lib/task/supervised.ex:121: Task.Supervised.exit/4
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

any idea why I see the `800` constant here? is it coming from the Master module? I don't use it.

**Comment by pallix** [comment]
I tried with 8000 as a timeout but I get this error:

```
** (exit) exited in: GenServer.call(#PID<0.4535.0>, {:read, 1024}, 5000)
    ** (EXIT) time out
Pid: #PID<0.4534.0>
```

Where does this 5000 come from?
